name: remote_config_feature_manager
description: Firebase Remote Config feature manager for developer preferences, experiments, A/B tests etc.
repository: https://github.com/theRealGetman/feature-manager/tree/master/packages/feature_manager_generator
issue_tracker: https://github.com/theRealGetman/feature-manager/issues

version: 3.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  feature_manager: ">=3.0.4 <4.0.0"
  shared_preferences: ">=2.1.2 <3.0.0"
  firebase_remote_config: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
